import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  titleContainer: {
    marginTop: 10,
    marginRight: 'auto',
    marginLeft: 'auto',
    width: 300,
  },
  bodyText: {
    fontSize: 17,
    color: 'black',
    textAlign: 'center',
  },
  sectionText: {
    fontSize: 15,
    color: 'black',
    textAlign: 'left',
    paddingLeft: 10,
    marginLeft: 10,
    marginBottom: 5,
  },
  innerSectionText: {
    fontSize: 12,
    color: 'black',
    textAlign: 'left',
    paddingLeft: 10,
    marginLeft: 20,
    marginTop: 2,
    marginBottom: 2,
  },
  stageText: {
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
    marginBottom: 5,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  buttonContainer: {
    marginRight: 'auto',
    marginLeft: 'auto',
    width: 220,
    height: 40,
    backgroundColor: '#65FF14',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fff',
    alignContent: 'center',
    justifyContent: 'center',
  },
  addButtonContainer: {
    marginLeft: 5,
    width: 30,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleInputMask: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 2,
    borderRadius: 20,
    marginBottom: 20,
    fontSize: 18,
    backgroundColor: '#fff',
    textAlign: 'center',
    paddingTop: 0,
    paddingBottom: 0,
  },
  styleInputMask: {
    height: 38,
    width: 200,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 15,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: '#fff',
    textAlign: 'center',
    marginTop: -10,
    marginRight: 'auto',
    marginLeft: 'auto',
    paddingTop: 0,
    paddingBottom: 0,
  },
  bodyInputMask: {
    height: 36,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 10,
    fontSize: 12,
    backgroundColor: '#fff',
    textAlign: 'center',
    paddingTop: 0,
    paddingBottom: 0,
  },
  smallBodyText: {
    marginLeft: 5,
    fontSize: 14,
    textAlign: 'center',
  },
  parametersRow: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 5,
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  parametersSecondRow: {
    display: 'flex',
    flexDirection: 'row',
    marginLeft: 10,
    marginTop: -2,
  },
  onePickerContainer: {
    backgroundColor: '#fff',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    width: 75,
    height: 36,
    marginLeft: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  onePicker: {
    width: 90,
    height: 36,
  },
  onePickerItem: {
    height: 36,
    color: 'black',
    fontSize: 12,
    textAlign: 'center',
  },
  onePickerContainerLarge: {
    backgroundColor: '#fff',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    width: 147,
    height: 36,
    marginLeft: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  onePickerLarge: {
    width: 160,
    height: 36,
  },
  signContainer: {
    height: 36,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredBodyTextContainer: {
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  confirmButton: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginTop: 10,
    width: 100,
    marginRight: 'auto',
    marginLeft: 15,
    backgroundColor: '#2196F3',
  },
  cancelButton: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginTop: 10,
    width: 100,
    marginRight: 'auto',
    marginLeft: 'auto',
    backgroundColor: '#99C7EB',
  },
  modalText: {
    marginBottom: 5,
    fontSize: 15,
    textAlign: 'center',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  rowContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  sectionHeaderContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 'auto',
    alignItems: 'center',
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 20,
    padding: 15,
    color: '#000',
  },
  sectionHeaderText: {
    fontSize: 17,
    color: 'black',
    textAlign: 'center',
    paddingLeft: 10,
    marginLeft: 10,
  },
  bodySectionText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'black',
    textAlign: 'center',
    marginLeft: 10,
    width: '50%',
    height: 35,
    lineHeight: 35,
  },
  bodySectionValue: {
    fontSize: 13,
    color: 'black',
    textAlign: 'center',
    marginLeft: 2,
    height: 35,
    lineHeight: 35,
  },
  sectionItem: {
    height: 35,
    lineHeight: 35,
    marginTop: 5,
    backgroundColor: '#E5E5E5',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    borderColor: '#C1BBBB',
    borderWidth: 1,
    borderRadius: 2,
  },
  sectionContainer: {
    marginLeft: '7%',
    marginRight: '7%',
    marginTop: 10,
  },
  itemButtonContainer: {
    marginLeft: 7,
    marginRight: 7,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
    lineHeight: 35,
  },
  itemValuesArea: {
    width: '10%',
    display: 'flex',
    flexDirection: 'row',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    minHeight: '100%',
  },
  loadingText: {
    textAlign: 'center',
    fontSize: 15
  }
});
